basePath: /
definitions:
  main.InputData:
    properties:
      created_at:
        example: "2023-05-22T14:56:32Z"
        type: string
      description:
        example: Descrição detalhada do item
        maxLength: 200
        type: string
      email:
        example: usuario@exemplo.com
        type: string
      name:
        example: Nome do Item
        maxLength: 50
        minLength: 3
        type: string
      value:
        example: 123ABC
        minLength: 1
        type: string
    required:
    - name
    - value
    type: object
  main.Response:
    properties:
      data: {}
      message:
        type: string
      status:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Uma API simples construída em Go usando Gin framework.
  title: Callable API
  version: "1.0"
paths:
  /api/v1/data:
    get:
      description: Retorna uma lista de itens disponíveis
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
      summary: Obtém lista de dados
    post:
      consumes:
      - application/json
      description: Adiciona um novo item com base nos dados fornecidos
      parameters:
      - description: Dados do item
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/main.InputData'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
      summary: Cria um novo item
  /api/v1/data/{id}:
    get:
      description: Retorna um item específico com base no ID fornecido
      parameters:
      - description: ID do item
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
      summary: Obtém item por ID
  /health:
    get:
      description: Retorna um status 200 se a API estiver rodando
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
      summary: Verifica o status da API
swagger: "2.0"
